name: Deploy demo

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: Deploy demo
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Server
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          SSH_SERVER_PRIVATE_KEY : ${{ secrets.MAIN_PRIVATE_KEY }}
          SSH_SERVER_IP: ${{ secrets.MAIN_IP }}
          SSH_SERVER_USER_NAME: ${{ secrets.MAIN_USER_NAME }}
        run: |
          mkdir -p $HOME/.ssh/
          echo "$SSH_SERVER_PRIVATE_KEY" > $HOME/.ssh/id_ed25519 && chmod 600 $HOME/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_ed25519 "${SSH_SERVER_USER_NAME}@${SSH_SERVER_IP}" "/home/${SSH_SERVER_USER_NAME}/scripts/deploy-${REPO_NAME}.sh"

      - name: Remove PEM Files
        run: |
          rm -f $HOME/.ssh/id_ed25519
